### ISSUE TITLE
wordpress plugin not working on replica of live site

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/wordpress-oxd-plugin#4]
Hi Vlad,

The wordpress plugin is not working on devsite.gluu.org which is replica of live site.
Please have a look. Two screenshots are attached. One showing that plugin is installed and the other one showing that SSO screen is not showing on login screen.

![openid_installed](https://cloud.githubusercontent.com/assets/1020315/22874759/e142b568-f1ed-11e6-9ef8-4f59638bc83c.png)
![openid_not_working](https://cloud.githubusercontent.com/assets/1020315/22874760/e6989b4a-f1ed-11e6-8f28-aa3922800477.png)

**Comment by karapetyan88** [comment]
done
