### ISSUE TITLE
error in activating plugin

### ISSUE THREAD

**Issue by MohammadKani** [GluuFederation/wordpress-oxd-plugin#5]
i installed plugin in local system and it's work fine.
but when i try to activate it on server it get following error:
Parse error: syntax error, unexpected '[' in /var/www/vhosts/roozbahan.com/httpdocs/wp-content/plugins/openid-connect-sso-by-gluu/gluu_openid_oxd_settings.php on line 109

witch is point to this code 

$config_option = array(
				"oxd_host_port" =>8099,
				"authorization_redirect_uri" => site_url().'/index.php?option=oxdOpenId',
				"logout_redirect_uri" => site_url().'/index.php?option=allLogout',
				"scope" => [ "openid", "profile","email"],
				"application_type" => "web",
				"redirect_uris" => [ site_url().'/index.php?option=oxdOpenId' ],
				"response_types" => ["code"],
				"grant_types" =>["authorization_code"],
				"acr_values" => []
			);

it's look like that php got error on creating array on params

**Comment by mzico** [comment]
Please create a ticket in https://support.gluu.org
