### ISSUE TITLE
Missing classes in version 3.1.1

### ISSUE THREAD

**Issue by Richard-NL** [GluuFederation/wordpress-oxd-plugin#6]
Hi, I just updated the plugin to from version 3.0.1 to 3.1.1
I noticed the following commit:
https://github.com/GluuFederation/wordpress-oxd-plugin/commit/3b33f8c60136529e820be18496b6208452de563f#diff-f17b30e0446eab7f518876e14dd32c35

I don't see those files in the oxd-rp in both tagged version and master version. Did someone forget some files?

**Comment by centroxy** [comment]
@Richard-NL  Your issue is not clear. We have not merged to master  branch. The plugin for version 3.1.1 is available at 3.1.1 branch

**Comment by Richard-NL** [comment]
You can close the issue I had missing files when running auto update. in wordpress. However this was not due to a wrong commit, but rather a file permission setting fault on my side
